#a <- as.Date("2015-10-27")
#startToASB <- seq(a,length.out = 108,by = "1 day")
#startToASBLabsForm <- format(startToASB,format="%m_%d_%Y")
#startToASBLabsFormDF <- data.frame(startToASBLabsForm,stringsAsFactors = FALSE)
#asbToEnd <- as.Date("2016-2-18")
#asbToEndDF <- seq(asbToEnd,length.out = 56,by = "1 day")
#asbToEndLabsForm <- format(asbToEndDF,format="%m_%d_%Y")
#asbToEndLabsFormDF <- data.frame(asbToEndLabsForm,stringsAsFactors = FALSE)
